version: "3.8"

services:
  db:
    image: postgres:15  
    container_name: user-tracker-database  
    restart: always  
    environment:
      POSTGRES_USER: postgres  
      POSTGRES_PASSWORD: password  
      POSTGRES_DB: postgres  
    ports:
      - '5432:5432'  
    volumes:
      - ./backend/DBBackup/init.sql:/docker-entrypoint-initdb.d/init.sql  
      - postgres_data:/var/lib/postgresql/data  
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]  
      interval: 5s  
      timeout: 10s  
      retries: 5  

  api:
    build: ./backend  
    container_name: user-tracker  
    restart: always  
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 3000:3000

volumes:
  postgres_data: user-tacker-data
